## Autonome 用の APIを叩く http リクエスト
@baseUrl=https://autonome.alt.technology/web3-dev-eesyph

### POST Request
POST {{baseUrl}}/chat
Content-Type: application/json
Authorization: Basic d2ViMy1kZXY6VHJJa051WEJQSg==

{
  "message": "what is my wallet's balance (ETH & USDC) now?"
}


## これは動かないメソッド

### agents APIを呼び出す
GET {{baseUrl}}/agents
Authorization:Basic d2ViMy1kZXY6VHJJa051WEJQSg==

{}
