# API Endpoint
@baseUrl = http://localhost:3000
# ここは各自デプロイした結果によって異なります。
# @baseUrl = https://hono-vertexai-image-tbj5qgjmvq-uc.a.run.app

### GET /
GET {{baseUrl}}/

### GET /health
GET {{baseUrl}}/health

### POST /agentVertexAI
POST {{baseUrl}}/agentVertexAI
Content-Type: application/json

{
  "prompt": "アカウントが sepolia ネットワークで50 USDC以上の USDCを保有している場合、 WETHにSwapしてください。 結果に以下を含めてください: - アカウントの新しい担保状況 - トランザクションハッシュ - トランザクションステータス"
}

### POST /runCdpChatMode
POST {{baseUrl}}/runCdpChatMode
Content-Type: application/json

{
  "prompt": "What is my wallet's balance (ETH & USDC) now?"
}

## "prompt": "What is my wallet's balance (ETH & USDC) now?"
## "prompt": "Please register myTestDomain to basename"
## "prompt": "Cloud you fund ETH (faucet) to my wallet on base-sepolia?"
## "prompt": "Cloud you send 0.001ETH from my wallet to 0x51908F598A5e0d8F1A3bAbFa6DF76F9704daD072?"
## "prompt": "Please sign message to 'Hi, I'm a human.' "

### POST /runChatGroqAgent
POST {{baseUrl}}/runChatGroqAgent
Content-Type: application/json

{
  "prompt": "アカウントが 50 USDC以上の USDCを保有している場合、 WETHにSwapしてください。 結果に以下を含めてください: - アカウントの新しい担保状況 - トランザクションハッシュ - トランザクションステータス"
}


## "prompt": "アカウントが Holeskyで 10ETH以上保有している場合、 10ETHを使ってステーキングしてください。 結果に以下を含めてください: - アカウントの新しい担保状況 - トランザクションハッシュ - トランザクションステータス"
##


### POST /runCryptOpenAIAgent
POST {{baseUrl}}/runCryptOpenAIAgent
Content-Type: application/json

{
  "prompt": "アカウントが 50 USDC以上の USDCを保有している場合、 WETHにSwapしてください。 結果に以下を含めてください: - アカウントの新しい担保状況 - トランザクションハッシュ - トランザクションステータス"
}

### POST /runCryptoVertexAIAgent
POST {{baseUrl}}/runCryptoVertexAIAgent
Content-Type: application/json

{
  "prompt": "アカウントが 50 USDC以上の USDCを保有している場合、 WETHにSwapしてください。 結果に以下を含めてください: - アカウントの新しい担保状況 - トランザクションハッシュ - トランザクションステータス"
}


### POST /discussion
POST {{baseUrl}}/discussion
Content-Type: application/json

{
  "prompt": "私は、 sepoliaとholeskyでいくらか暗号資産を保有しています。今、自分の資産を一番効率的に増やすためには何をしたら良いでしょうか？"
}
