# API Endpoint
#@baseUrl = http://localhost:3000
# This will vary depending on the results of each deployment.
@baseUrl = https://hono-vertexai-image-tbj5qgjmvq-uc.a.run.app

### GET /
GET {{baseUrl}}/

### GET /health
GET {{baseUrl}}/health

### POST /agentVertexAI
POST {{baseUrl}}/agentVertexAI
Content-Type: application/json

{
  "prompt": "Please tell me the latest news about Web3 or cryptocurrency or blockchain. I have to plan to swap some token on sepolia.",
  "operation": "SocialTrend"
}

##  "prompt": "If I want to grow my assets by swapping, lending, or staking cryptocurrencies, what should I do?",
##  "prompt": "Please collect trend information related to Web3.",
##  "operation": "SocialTrend"
##  "prompt": Please collect the latest news about Web3.",
##  "operation": "NewsAndFundamentals"
##  "operation": "RiskManagement"
##  "operation": "PerformanceMonitoring"
##  "operation": "AnalysisAndReasoning"
##  "operation": "DeFi"

### POST /runChatGroqAgent
POST {{baseUrl}}/runChatGroqAgent
Content-Type: application/json

{
  "prompt": "If your account has more than 5 USDC in the Arbitrum Sepolia network, please lend 5 USDC. Please include the following in the results: - The account's new collateral status - The transaction hash - The transaction status"
}


## "prompt": "If your account has more than 10 ETH in Holesky, please stake 10 ETH. Please include the following in the results: - New collateral status of the account - Transaction hash - Transaction status"
## "prompt": "If your account has more than 5 USDC in the Arbitrum Sepolia network, please lend 5 USDC. Please include the following in the results: - The account's new collateral status - The transaction hash - The transaction status"


### POST /runCryptOpenAIAgent
POST {{baseUrl}}/runCryptOpenAIAgent
Content-Type: application/json

{
  "prompt": "Collect the latest news on Web3.",
  "operation": "NewsAndFundamentals"
}

## "prompt": "If your account has more than 5 USDC in the Arbitrum Sepolia network, please lend 5 USDC. Please include the following in the results: - The account's new collateral status - The transaction hash - The transaction status"
## "prompt": "If your account has 1stETH or more in Holesky, please re-stake 1stETH. Please include the following in the results: - New collateral status of the account - Transaction hash - Transaction status"


### POST /runAnthropicAIAgent
POST {{baseUrl}}/runAnthropicAIAgent
Content-Type: application/json

{
  "prompt": "Please tell me the latest news about Web3 or cryptocurrency or blockchain. I will lend some token on base sepolia.",
  "operation": "SocialTrend"
}

## sepolia, arbitrum sepolia, or holesky.
