name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-build-and-test:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # pnpm をセットアップ
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          # 必要に応じて pnpm のバージョンを変更してください
          version: 8.9.1

      # 依存関係のインストール
      - name: Install dependencies
        run: pnpm install
